<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Macademy\Jumpstart\ViewModel\WelcomeMessage $welcomeMessageViewModel */
$welcomeMessageViewModel = $block->getData('welcome_message_view_model');
?>
<div style="text-align: center; margin-top: 50px;">
    <h1 style="font-size: 36px; color: #333; font-family: Arial, sans-serif;">
        <?= $welcomeMessageViewModel->getWelcomeMessage() ?>
    </h1>
</div>
