<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="header-banner">
    <div class="header-banner__slider">
        <div class="content-element-container center-block">
         
        </div>
    </div>
</div>



<div class="content-element-container">
    <div class="element-container product-list-horizontal">
        <div class="element-header-container">
            <div class="header-text">Discover Milia Matcha</div>
        </div>
        <div class="product-list-slider">
            <div class="product-container">
                <img class="product-container__image icons" src="<?= $block->getViewFileUrl('images/discount.png'); ?>" />
                <div class="title">Shop in 7 countries</div>
            </div>
            <div class="product-container">
                <img class="product-container__image icons" src="<?= $block->getViewFileUrl('images/discount.png'); ?>" />
                <div class="title">Secure payments</div>
            </div>
            <div class="product-container">
                <img class="product-container__image icons" src="<?= $block->getViewFileUrl('images/discount.png'); ?>" />
                <div class="title">Deals and promotions</div>
            </div>
        </div>
    </div>
</div>

<div class="content-element-container trending">
    <div class="element-container product-list-horizontal">
        <div class="element-header-container">
            <div class="header-text">Les Matcha</div>
            <a class="learn-more" href="<?php echo $this->getUrl('catalog/category/view', ['id' => 3]); ?>">Shop now</a>
        </div>
        <div class="product-list-slider">
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/cerice2.jpg'); ?>" />
            </div>
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/CEREMONIE_.jpg'); ?>" />
            </div>
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/FRAISEFINALPP.jpg'); ?>" />
            </div>
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/vanille2.jpg'); ?>" />
            </div>
        </div>
    </div>
</div>

<div class="content-element-container">
    <div class="element-container product-list-horizontal">
        <div class="element-header-container">
            <div class="header-text">Nos Accessoires</div>
            <a class="learn-more" href="#">Shop now</a>
        </div>
        <div class="product-list-slider">
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/MILIA_PACKSHOT_9.jpg'); ?>" />
            </div>

            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/MILIA_PACKSHOT_4.jpg'); ?>" />
            </div>
            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/MILIA_PACKSHOT_9.jpg'); ?>" />
            </div>

            <div class="product-container">
                <img class="product-container__image" src="<?= $block->getViewFileUrl('images/MILIA_PACKSHOT_4.jpg'); ?>" />
            </div>
        </div>
    </div>
</div>
