<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>


<div class="custom-block-left-image">
    <div class="custom-block-left-image-left">
        <img src="<?php echo $block->getViewFileUrl('images/MILIA_ANDIE_3.jpg'); ?>" alt="Another Custom Image" />
    </div>
    <div class="custom-block-left-image-right">
       <h2>"MADAME MATCHA"</h2>
       <p>Sa maman lui en préparait le matin pour l’aider à « se concentrer » avant d’aller à l’école, et elle n’a depuis jamais perdu cette habitude !</p>

    </div>
</div>
<div class="custom-block">
    <div class="custom-block-left">
        <h2>DEPUIS L'ENFANCE</h2>
        <p>Dès son plus jeune âge, Andie est plongée dans l’univers du thé matcha. En 2010, sa mère lui faisait découvrir le matcha à travers tous les grands salons professionnels alimentaires en France et évoquait déjà les bienfaits de cette boisson lors de conférences.</p>
       <p>Sa maman lui en préparait le matin pour l’aider à « se concentrer » avant d’aller à l’école, et elle n’a depuis jamais perdu cette habitude !</p>
    </div>

    <div class="custom-block-right">
        <img src="<?php echo $block->getViewFileUrl('images/andie-12.jpg'); ?>" alt="Custom Image" />
    </div>
</div>

<div class="custom-block">
    <div class="custom-block-left">
        <h2>LE RÊVE DU JAPON</h2>
        <p>Après avoir attendu des années avant de pouvoir enfin visiter le Japon, elle réalise son rêve qu’elle partage avec ses centaines de milliers d’abonnés qui la suivent dans cette aventure. C’est le début d’une grande histoire…</p>

    </div>

    <div class="custom-block-right">
        <img src="<?php echo $block->getViewFileUrl('images/DSCF3626.jpg'); ?>" alt="Custom Image" />
    </div>
</div>
